feat: SNLX-34 show local books
Solify-IT/snorlax pull request #21
Opened 2021-04-29 17:56 UTC by KevinWoolfolk

#### ¿Qué hace este PR?![image](https://user-images.githubusercontent.com/42701464/116595374-e010ab80-a8e8-11eb-91c9-23909058b60d.png)Este PR muestra la busqueda de libros de forma local(librería interna) y de forma global(Todas las librerías de la RELI).

#### ¿Cómo debería ser probado manualmente?

Antes de hacer alguna prueba tenemos que tener libros en la base de datos y librerias.
La libreria tiene que tener el siguiente uid: e11e5635-094c-4224-836f-b0caa13986f3
En caso de querer cambiarla nos vamos al archivo Search.LocalBooksList/LocalBooksList.compound.tsx en la linea 23 cambiar el uid.

Una vez que tengamos la base de datos bien nos vamos a la siguiente liga:
http://localhost/inventario/libros/buscar-local

![image](https://user-images.githubusercontent.com/42701464/116595374-e010ab80-a8e8-11eb-91c9-23909058b60d.png)

En busqueda local se pueden buscar libros con isbn que esten  con ese uid de libreria.
En busqueda global se pueden buscar todos los libros de la base de datos.

#### ¿Cuáles son los tickets relevantes? 
[SNLX-34](https://snorlax-reli.atlassian.net/jira/software/projects/SNLX/boards/1/backlog?selectedIssue=SNLX-34)
[SNLX-22](https://snorlax-reli.atlassian.net/jira/software/projects/SNLX/boards/1/backlog?selectedIssue=SNLX-22)

#### Checklist

**Assignees:**
- [ ] Añadí la documentación necesaria, si es necesario. 
- [ ] Agregué tests para probar que mi código funciona
- [ ] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-04-29 18:25 UTC, Topi99 requested changes
Dejo unos comentarios con recomendaciones y sugerencias de cambios.

* Elimina el archivo `.DS_Store`, puedes añadirlo al archivo `.gitignore`. 
* Corre el comando `yarn lint --fix` tanto en el frontend como backend.

2021-04-29 18:25 UTC, Topi99 commented on backend/src/interface/controller/bookController.ts
>      );
¿Se usa esta función en el controlador? No encuentro usos de esta función.

2021-04-29 18:25 UTC, Topi99 commented on frontend/src/Components/Router/Router.tsx
> +        {/* <Route exact path={LIST_LOCAL_BOOKS} component={LocalBooksListView} /> */}
Hay que eliminar este código comentado.

2021-04-29 18:25 UTC, Topi99 commented on frontend/src/Components/Router/routes.ts
> +export const LIST_LOCAL_BOOKS = `${BOOKS}/buscar-local`;
Aquí sugiero que cambiemos a esto:
```suggestion
export const LIST_LOCAL_BOOKS = `${BOOKS}/buscar`;
```

2021-04-29 18:25 UTC, Topi99 commented on frontend/src/views/Search.LocalBooksList/LocalBooksList.compund.tsx
> +const LocalBooksList: React.FC = () => {
Hay que revisar el formato de este archivo, tiene muchos errores de estándares. Te recomiendo correr `yarn lint --fix` para arreglar la mayoría.

2021-04-29 18:25 UTC, Topi99 commented on frontend/src/views/Search.LocalBooksList/LocalBooksList.compund.tsx
> +      console.log(values.isbn);
No debemos tener `console.log`s en código de producción. Revisa todas tus cambios por si hay más.

2021-04-29 18:25 UTC, Topi99 commented on frontend/src/views/Search.LocalBooksList/LocalBooksList.tsx
> +}) => {
Me parece que tenemos duplicado este componente. Revisa la carpeta de componentes y elimina alguno de los duplicados.

2021-05-03 16:21 UTC, Topi99 approved these changes
Gracias @KevinWoolfolk, funciona muy bien, LGTM 💯 . Solamente tengo unos comentarios acerca del estilo del buscador, pero los podemos arreglar en un futuro.

2021-05-03 21:40 UTC, JuanCarlosCV approved these changes

2021-05-04 00:04 UTC, merged

2021-05-04 00:04 UTC, Topi99 commented
:shipit: