Snlx 33 getbookdetails
Solify-IT/snorlax pull request #22
Opened 2021-05-03 19:44 UTC by JuanCarlosCV

#### ¿Qué hace este PR?
Este PR es para poder visualizar los detalles en cada libro, desde la vista inventario se pueden seleccionar y ver la información.
#### ¿Cómo debería ser probado manualmente?
Antes de hacer alguna prueba tenemos que tener libros en la base de datos y librerias.
La libreria tiene que tener el siguiente uid: e11e5635-094c-4224-836f-b0caa13986f3
-Los pasos anteriores son básicos para visualizar libros
Debe ser probado manualmente en tu dispositivo local
Accede 
http://localhost/inventario/libros
![image](https://user-images.githubusercontent.com/36903314/116922047-6c3d0e80-ac1a-11eb-9084-b4b68df52f72.png)
Se debe ver los libros como el ejemplo de arriba, puedes acceder a la información con un click en su titulo o en el botón azul en cada fila del libro.
![image](https://user-images.githubusercontent.com/36903314/116924732-e327d680-ac1d-11eb-9c63-c36f9715dcdd.png)

#### ¿Algún background que desees proveer? 

#### ¿Cuáles son los tickets relevantes? 

Usa el formato: SNLX-XX

#### Screenshots

#### Preguntas

#### Checklist

**Assignees:**
- [x] Añadí la documentación necesaria, si es necesario. 
- [x] Agregué tests para probar que mi código funciona
- [x] Revisé PRs existentes antes de publicar el mío. 

**Reviewers:**
- [ ] La Inyección de dependencias es correcta.
- [ ] No se importan archivos de niveles superiores de la arquitectura. 
- [ ] Los nombres de variables, objetos, clases y demás son entendibles. 
- [ ] El CI/CD Pipeline pasa.

2021-05-04 00:20 UTC, A01702321 commented
Yo sugeriría no usar Forms, porque creo que haces los campos editables, o parecen ser editables. Unicamente se debe desplegar la información.

2021-05-04 01:14 UTC, Topi99 commented on backend/src/interface/controller/bookController.ts
> +  async getBookbyId(context: IContext): Promise<void> {
```suggestion
  async getBookById(context: IContext): Promise<void> {
```

2021-05-04 01:35 UTC, Topi99 requested changes
Gracias por los cambios @JuanCarlosCV, están funcionando muy bien. Por favor, revisa los comentarios, sugerencias y propuestas de cambio de código que te dejé abajo. Déjame saber qué piensas. 

También revisa el [Defect Log](https://docs.google.com/spreadsheets/d/1n2cWt93illUzUb792wIrKKC8qC9b37JRt8x2sTczUkk/edit#gid=1320741392) de este PR para obtener más detalles sobre mis comentarios.

2021-05-04 01:35 UTC, Topi99 commented on backend/src/interface/controller/bookController.ts
> +    const [books, error] = await wrapError(
```suggestion
    const [book, error] = await wrapError(
```

2021-05-04 01:35 UTC, Topi99 commented on backend/src/interface/repository/bookRepository.ts
> +  // regresar
Hay que borrar este comentario.

2021-05-04 01:35 UTC, Topi99 commented on backend/src/usecases/interactor/bookInteractor.ts
> +    console.log(localBook);
Hay que eliminar todos los console.log que encuentres.

2021-05-04 01:35 UTC, Topi99 commented on frontend/src/Components/Router/routes.ts
> -
Hay que dejar este espacio en blanco para dejar separación entre bloques de código con distinto propósito.

2021-05-04 01:35 UTC, Topi99 commented on frontend/src/views/Books.FormViewBook/FormViewBook.compund.tsx
> +const FormViewBook: React.FC = () => {
¿Por qué `FormViewBook` y no `BookDetailView`? Es un nombre más descriptivo de la intención del componente. Haz el cambio de nombre también en los archivos necesarios, por favor.

2021-05-04 01:35 UTC, Topi99 commented on frontend/src/views/Inventory.LocalBooksList/LocalBooksList.tsx
> +      title: '',
El título podría ser `Acciones`.
```suggestion
      title: 'Acciones',
```

2021-05-20 22:13 UTC, Topi99 approved these changes
Un pequeño comentario solamente. Sin defectos nuevos.

2021-05-20 22:13 UTC, Topi99 commented on backend/src/infrastructure/router/router.ts
> +    app.get('/books/:bookId', async (request, response, next) => {
Estaría bien que pusieras el middleware de autenticación, para que solo usuarios con sesión válida puedan consultar info de libros. 
```suggestion
    app.get('/books/:bookId', middleware, async (request, response, next) => {
```

Lo dejo a tu consideración.

2021-05-20 22:13 UTC, Topi99 commented on backend/src/interface/controller/bookController.ts
> +    const [book, error] = await wrapError(
Aquí si debe ser "books":
```suggestion
    const [books, error] = await wrapError(
```

2021-05-20 22:13 UTC, Topi99 commented on backend/src/interface/controller/bookController.ts
> +    context.response.status(200).json({ ...book });
Igual aquí debe ser "books"
```suggestion
    context.response.status(200).json({ ...books });
```

2021-05-20 22:13 UTC, Topi99 commented on backend/src/usecases/interactor/bookInteractor.ts
> +  [x: string]: any;
¿Por qué se necesitó este cambio?

2021-05-20 22:13 UTC, Topi99 commented on frontend/src/views/Books.FormViewBook/FormViewBook.compund.tsx
> +const FormViewBook: React.FC = () => {
Sigo pensando lo mismo.

2021-05-20 22:13 UTC, Topi99 commented on frontend/src/views/Search.LocalBooksList/LocalBooksList.tsx
> +      title: '',
Solo aquí pon esto:
```suggestion
      title: 'Acciones.',
```

2021-05-20 22:24 UTC, JuanCarlosCV commented on backend/src/usecases/interactor/bookInteractor.ts
> +  [x: string]: any;
esto si no recuerdo porque se hizo

2021-05-20 22:41 UTC, JavierIQ approved these changes

2021-05-20 22:42 UTC, merged

2021-05-20 22:43 UTC, A01702321 approved these changes